---
- hosts: nodes,iot-devices
  roles:
  become: yes
  vars:
    facts_path: "/var/lib/xdata-infra"
    facts_owner: "sasano8"
    facts_group: "xdata_ansible"


- name: Cleanup facts directory
  hosts: localhost
  gather_facts: false  # factsの収集を無効にする（高速化）
  tasks:
    - name: Cleanup facts directory
      become: yes
      file:
        path: "{{ facts_path }}"
        state: absent

    - name: Make facts directory
      become: yes
      file:
        path: "{{ facts_path }}"
        state: directory
        owner: "{{ facts_owner }}"
        group: "{{ facts_group }}"
        mode: "0770"

- name: Gather Facts and save as JSON
  hosts: nodes,iot-devices
  tasks:
    # setupはgather_facts=yesと同じ。明示的に呼び出すために使用する。
    - name: Setup module to gather facts
      setup:

    - name: Save facts to a JSON file
      delegate_to: localhost
      copy:
        content: "{{ ansible_facts | to_nice_json }}"
        dest: "{{ facts_path }}/{{ inventory_hostname }}.json"  # TODO: playbookのパスからの相対パスになる。ちょっと危険
