ansible-playbook -i inventry/hosts.development.yml site.yml
ansible-playbook -i inventry/hosts.development.yml playbooks/get_spec.yml
ansible-playbook -i inventry/hosts.development.yml playbooks/get_spec.yml --ask-become-pass
